### ISSUE TITLE
Protocol error 1 on object wl_display@1: invalid arguments for wl_shm@6.create_pool

### ISSUE THREAD

**Issue by Supreeeme** [Supreeeme/xwayland-satellite#12]
Observed running satellite with `XWAYLAND_NO_GLAMOR=1` and launching Nemo.

Also observerd in:
- Steam - sporadically after launching SteamVR
- AvaloniaIlSpy

Related issues:
https://gitlab.freedesktop.org/xorg/xserver/-/issues/1283
https://github.com/swaywm/sway/pull/6629
https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2235

**Comment by YaLTeR** [comment]
This fixed it in niri + rootful Xwayland: https://github.com/YaLTeR/niri/commit/bcca03cce7da9dc4125aa34943041cb65e0fd4bb

I think you need to do the same here, then it'll work.

**Comment by Supreeeme** [comment]
I appear to have a (hacky) fix for this, so closing.
