### ISSUE TITLE
Javascript error whenever opening an X11 application

### ISSUE THREAD

**Issue by Damnjelly** [Supreeeme/xwayland-satellite#33]
Whenever I open an X11 application (e.g vesktop) while xwayland-satellite is active on the background I get the following error:
![image](https://github.com/Supreeeme/xwayland-satellite/assets/13944407/734d3349-67e0-4b21-be50-19112e724857)

When I press "Ok" this same error pops up 2 or 3 more times and then the application opens as usual. 

This I've tried to fix this issue:
- Change the display environment variable from 0 to 12 (and also launching xwayland-satellite with the same value of course)
- Change GPU and GPU drivers (RTX 3070 with proprietary drivers, RTX 3070 with mesa drivers and RX 6700 XT)

Other weird things I've noticed:
- Whenever vesktop is open and I open a separate X11 application, then vesktop freezes whenever the error popup is open.

Specs:
- DE: niri unstable 2024-06-22 (commit ebaf1b06205bbf6bae2697a7b025665d3c244478)
- OS: NixOS 24.11
- CPU: AMD Ryzen 5 5600X
- GPU (currently): AMD Radeon RX 6700 XT

**Comment by sodiboo** [comment]
This isn't really a solution to the issue, but a workaround would be to run vesktop as a Wayland client. Is there any particular reason you run it as an X11 client? Try `NIXOS_OZONE_WL=1 vesktop`

**Comment by Damnjelly** [comment]
I tried setting `NIXOS_OZONE_WL=1` following your comment and I still get the same javascript error, even without xwayland-satellite running. 
I've also tried going back to my old solution (running I3 inside of niri) and that produces the same error aswell. So I've misattributed my issue on xwayland-satellite.
