### ISSUE TITLE
`Error getting buffer` when gaming on another VT

### ISSUE THREAD

**Issue by my4ng** [Supreeeme/xwayland-satellite#38]
When I play a game on another VT in a different user + DE, the xwayland-satellite window becomes unresponsive afterwards:

```
Jul 07 20:08:09 fedora xwayland-satellite[137817]:  2024-07-07T10:08:09.703Z INFO  xwayland_process                  > src/nv_gbm.c:123: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
Jul 07 20:08:09 fedora xwayland-satellite[137817]:  2024-07-07T10:08:09.703Z INFO  xwayland_process                  >
Jul 07 20:08:44 fedora xwayland-satellite[137817]:  2024-07-07T10:08:44.706Z INFO  xwayland_process                  > src/nv_gbm.c:123: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
Jul 07 20:08:44 fedora xwayland-satellite[137817]:  2024-07-07T10:08:44.706Z INFO  xwayland_process                  >
Jul 07 20:08:44 fedora xwayland-satellite[137817]:  2024-07-07T10:08:44.706Z INFO  xwayland_process                  > src/nv_gbm.c:123: GBM-DRV error (nv_gbm_bo_create): DRM_IOCTL_NVIDIA_GEM_ALLOC_NVKMS_MEMORY failed (ret=-1)
Jul 07 20:08:44 fedora xwayland-satellite[137817]:  2024-07-07T10:08:44.706Z INFO  xwayland_process                  >
Jul 07 20:08:45 fedora xwayland-satellite[137817]:  2024-07-07T10:08:45.707Z INFO  xwayland_process                  > Error getting buffer
```

I suspect this may be a technical limitation with , but will it be possible to retry getting buffer after the game window has been closed and switched back to orginal VT, for example indicated by mouse/keyboard input?

**Comment by Supreeeme** [comment]
Sorry, I'm a little confused about the scenario. To clarify, are you saying that you:
- Have a compositor with xwayland-satellite running on one TTY, then switch to another TTY with a different compositor not using xwayland-satellite and open a game
- Come back to the first TTY and xwayland-satellite stops working?

I'm not able to reproduce this, if that's what you were saying. It seems at least to be Nvidia related, but I have an AMD card. In any case, this message is originating from Xwayland itself, and I don't think it really provides any meaningful feedback or way to know that getting a buffer failed, whatever that even means.

**Comment by my4ng** [comment]
> To clarify, are you saying that you:
Yes that sequence is exactly correct. I am using KDE plasma 6.1 on the other VT which has kwin. 

From the log messages, it seems to be an nvidia issue. I will try to gather more logs but it seems to be non-xwayland-satellite specific, so I will just close this for now.
