### ISSUE TITLE
issue with the installation!

### ISSUE THREAD

**Issue by r4hulrosh4n** [Supreeeme/xwayland-satellite#40]
![2024-07-15 01-24-09](https://github.com/user-attachments/assets/0573e012-b42b-449e-baa1-1cb0ce425018)

**Comment by Supreeeme** [comment]
You seem to be missing the `xcb-util-cursor` library.l

**Comment by r4hulrosh4n** [comment]
![image](https://github.com/user-attachments/assets/047e9fd0-92bd-4d7d-95b4-4d8628e58aea)

**Comment by Supreeeme** [comment]
What's the bottom part of that error?

**Comment by Supreeeme** [comment]
I'll assume you figured this out.
