### ISSUE TITLE
Steam main window not showing

### ISSUE THREAD

**Issue by vanarok** [Supreeeme/xwayland-satellite#43]
![Screenshot from 2024-07-24 13-07-11](https://github.com/user-attachments/assets/a590ee16-dc7f-4df7-8c85-fa914dc53c9f)
![Screenshot from 2024-07-24 13-07-17](https://github.com/user-attachments/assets/278fc770-bae7-4794-80b7-480af9948723)
![Screenshot from 2024-07-24 13-08-43](https://github.com/user-attachments/assets/29e47ade-acc3-4c2a-a8a1-631e0b5a7c69)
Installed xwayland-satellite 0.4.r15.g8892570-1

The windows: login, messages, account selection are all fine

**Comment by FreeFull** [comment]
This happens if you have the "Enable GPU accelerated rendering in web views" setting enabled in Steam's settings. Once you disable that, there's still another bug you'll have to deal with: When starting steam, the main window won't redraw properly until you resize it at least once.

**Comment by Titaniumtown** [comment]
> This happens if you have the "Enable GPU accelerated rendering in web views" setting enabled in Steam's settings. Once you disable that, there's still another bug you'll have to deal with: When starting steam, the main window won't redraw properly until you resize it at least once.

Thank you for this tip, I couldn't figure out how to get steam to actually display anything.

**Comment by Supreeeme** [comment]
I haven't seen this happen in a while and I have the GPU accelerated rendering option on and steam seems fine now, so I'm gonna close this.
