### ISSUE TITLE
File picker doesnt appear

### ISSUE THREAD

**Issue by cbjx** [Supreeeme/xwayland-satellite#48]
When try to open file picker, like vivaldi and vesktop, nothing happens.
Vivaldi with wayland backend shows file picker normally.

**Comment by cbjx** [comment]
[log.txt](https://github.com/user-attachments/files/16634552/log.txt)
Using niri 0.1.8, running vivaldi and trying to open file picker

**Comment by cyrneko** [comment]
Maybe this should be re-opened, I can replicate the same issue running under `Niri 0.1.8 (9063a5d)` running `xwayland-satellite` from [this  copr repo](https://copr.fedorainfracloud.org/coprs/errornointernet/packages/package/xwayland-satellite/)

Anything running under XWayland seems completely unable to use portals, including the file picker, the screen sharing display picker, and even calling for the browser from within an XWayland app (e.g Tuba opening the Mastodon Auth Page)

I have not yet tested this with anything other than the [LibreWolf](https://flathub.org/apps/io.gitlab.librewolf-community) and [Tuba](https://flathub.org/apps/dev.geopjr.Tuba) Flatpaks, so them being Flatpaks may also be a factor in this issue.
