### ISSUE TITLE
pressing mf "ok" in mumble crashes the server 💀

### ISSUE THREAD

**Issue by exhq** [Supreeeme/xwayland-satellite#57]
https://github.com/user-attachments/assets/337cff42-31db-45b2-83a5-c36e73fe53e1

**Comment by ashley-graves** [comment]
blud thought they could press "ok" :skull:

**Comment by exhq** [comment]
i would also like to mention, pressing escape which does the same thing doesnt crash the server 💀

**Comment by Supreeeme** [comment]
Are you on the latest git revision?

**Comment by exhq** [comment]
nope, aur/xwayland-satellite
ill check aur/xwayland-satellite-git

**Comment by exhq** [comment]
seems to be fixed on the git version ty sis
