### ISSUE TITLE
Automatically redirect X windows

### ISSUE THREAD

**Issue by alicealysia** [Supreeeme/xwayland-satellite#59]
Hi, just want to start off by saying this project is amazing. I wanted to request a feature that... doesn't strike me as easy to implement. 
I'm wondering if it's at all possible to redirect X windows to the xwayland-satellite display? Is this something that could be added to xwayland-satellite, or would this need to be done some other way... if it's even possible at all.

**Comment by alicealysia** [comment]
Good point. Basically, rather than needing to add env DISPLAY= <xwayland-satellite display number> to the start of any commands or .desktop files, it'd be increadible if we could automatically send the right windows to the right displays.

**Comment by Supreeeme** [comment]
That is something that is satellite can't do on it's own, but is easy to do via other means. All you need to do is set DISPLAY in your compositor's environment. One way of doing this is via a systemd service (an example one is in the repo) and having it start up with your compositor. Another way is to use your compositor's facilities for setting the environment on startup. For example, with niri, you could add this to your config file:
```
environment {
    DISPLAY ":0"
}
```
