### ISSUE TITLE
problem with 1passowrd (and possibly other tray-apps)

### ISSUE THREAD

**Issue by cptn-cosmo** [Supreeeme/xwayland-satellite#6]
I use 1password as a password manager, and while it works great with xwayland-satelleite (even integrates with the native browser extension and all!) the problem is that the app then keeps running in the tray. Once it is locked however, neither the browser plugin, nor the tray icon itself can restore the main window, which means i can't unlock it after it got locked due to timeouts - it works again after a reboot though.

**Comment by Supreeeme** [comment]
Are you still seeing this?

**Comment by Supreeeme** [comment]
Gonna close this, reopen if seen again
