### ISSUE TITLE
Copy image from firefox to discord (vesktop) crashes both and the entire xwayland-satellite server

### ISSUE THREAD

**Issue by zeroeightysix** [Supreeeme/xwayland-satellite#78]
Hi, not sure if this is the right place to report, but it's a starting point!

I'm running niri as compositor, firefox 133.0 (wayland native) and vesktop (`vesktop_electron` from the AUR, apparently removed since..) which is an X client.

Attempting to copy any image in firefox and paste it in vesktop will **freeze**
* firefox
* all clients connected to xwayland-satellite

All X clients become visually unresponsive, but my spotify playback did keep playing.

Killing (`pkill firefox`) firefox at this stage will crash vesktop (coredump backtrace [here](https://gist.github.com/zeroeightysix/ce47cca435f4baaf05e2825b5b39b900)) and panic xwayland-satellite ([here](https://gist.github.com/zeroeightysix/24d740865fb9b9b0e6abd4cb0d6e5c93)).

Is that enough to work with?

**Comment by Supreeeme** [comment]
Could you run xwayland satellite with `RUST_LOG=debug` and send the log?

**Comment by zeroeightysix** [comment]
Hi, sure can!
Here's the log: https://gist.github.com/zeroeightysix/ab2cb617734227e22141382034bfc3ab

Notably:
* `Wayland compositor doesn't seem to be processing events fast enough!` started as soon as I initiated the paste
* And it stopped (line 402) after `pkill firefox`.

**Comment by Supreeeme** [comment]
I am unfortunately unable to reproduce this. Tested with `vesktop-electron` from the AUR. What other X clients do you have running? Does this happen with any other apps?

**Comment by Supreeeme** [comment]
I will assume this was related to https://github.com/Supreeeme/xwayland-satellite/commit/94da1af75326d89ecb12aba0cc9362e93ffdc766.
