### ISSUE TITLE
Input doesn't work in Minecraft once in a world

### ISSUE THREAD

**Issue by FreeFull** [Supreeeme/xwayland-satellite#8]
It seems Minecraft almost works perfectly: Input works as expected while you're in menus.. But, once you join a world and the game captures the cursor, it ceases to accept any keyboard input or mouse movements (but clicking the mouse buttons does work). Once this gets fixed, the game should be 100% playable

**Comment by Supreeeme** [comment]
Hmm, the mouse cursor at least appears to be related to the pointer constraints global, but Xwayland refuses to use it after adding it locally. Will need to investigate more.

**Comment by FreeFull** [comment]
From playing around a bit more, it seems like xwayland-satellite is failing to give focus to the correct X11 window. Even while the minecraft window is focused in niri, the minecraft launcher seems to be getting keyboard events instead. I also saw something similar happen with xev and glxgears, but not 100% of the time

**Comment by Supreeeme** [comment]
> Even while the minecraft window is focused in niri, the minecraft launcher seems to be getting keyboard events instead.

How did you observe this?

**Comment by FreeFull** [comment]
While the minecraft window is focused by niri and the minecraft-launcher is visible on screen, hold down tab. For me, it ends up tabbing between various items in minecraft-launcher.

**Comment by Supreeeme** [comment]
Figured this one and got it working here, so I'll close it. The input focus was a good hint, thanks.
